language: ruby
rvm:
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - 2.3.7
  - 2.3.8
  - 2.4.0
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.5
  - 2.5.0
  - 2.5.1
  - 2.5.2
  - 2.5.3

script: bundle exec rake spec
env:
  - AWS_ACCESS_KEY=foo AWS_SECRET_ACCESS_KEY=bar
